= Contact Us

== Hours of Operation
School Hours - 8:30-3:30 +
Office Hours - 7:30-4:30

== Location
120 W Vine St. #200 Murray, UT 84107

++++
<center>
    <style>
      #map-canvas {
        width: 500px;
        height: 400px;
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script>
      function initialize() {
        var mapCanvas = document.getElementById('map-canvas');
        var mapOptions = {
          center: new google.maps.LatLng(40.662503, -111.894838),
          zoom: 18,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(mapCanvas, mapOptions)
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
 
    <div id="map-canvas"></div>
++++

== Contact Information
Phone - 801-948-3047 +
Fax - 801-639-9320

Attendance issues: attendance@wasatchinstitute.net +
General inquiries: info@wasatchinstitute.net

Contact our staff: +
David: david.moss@wasatchinstitute.net +
Leif: leif.nelson@wasatchinstitute.net +
Bill: bill.clark@wasatchinstitute.net +
Cory: cory.dixon@wasatchinstitute.net +
Gail: gail@wasatchinstitute.net

== Enroll Now
If you are interested in the Wasatch Institute of Technology and would like to enroll, fill out our <<EnrollNow.adoc#Enroll Now,online application>> and we will get back to you shortly.