= Contact Us
:sectanchors:

include::src/html/adoc/navbar.adoc[]


++++
       <div id="wrapper">
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href="#_hours_of_operation">Hours of operation</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_location">Location</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_contact_information">Contact information</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_why_donate">Why donate?</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_donate_now">Donate now</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_enroll_now">Enroll now</a>
                    </li>
                </ul>
            </div>
++++

== Hours of Operation
School Hours - 8:30-3:30 +
Office Hours - 7:30-4:30

== Location
120 W Vine St. #200 Murray, UT 84107

++++
<center>
    <style>
      #map-canvas {
        width: 500px;
        height: 400px;
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script>
      function initialize() {
        var mapCanvas = document.getElementById('map-canvas');
        var mapOptions = {
          center: new google.maps.LatLng(40.662503, -111.894838),
          zoom: 18,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(mapCanvas, mapOptions)
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
 
    <div id="map-canvas"></div>
++++

== Contact Information
Phone - 801-948-3047 +
Fax - 801-639-9320

Attendance issues: attendance@wasatchinstitute.net +
General inquiries: info@wasatchinstitute.net

Contact our staff: +
David: david.moss@wasatchinstitute.net +
Leif: leif.nelson@wasatchinstitute.net +
Bill: bill.clark@wasatchinstitute.net +
Cory: cory.dixon@wasatchinstitute.net +
Gail: gail@wasatchinstitute.net

== Make a donation
=== Why donate?
If you care about the future of technology and education, consider making a donation to the Wasatch Institute of Technology today. Not only will your donation go back into the community, you will be able to see the impact that it makes on our students and school. The return upon investment for this donation is the well-being of future employees in the tech sector. The Wasatch Institute of Technology is nurturing the greatest minds of today, and we hope to produce the greatest minds of tomorrow.

=== Donate now

== Enroll Now
If you are interested in the Wasatch Institute of Technology and would like to enroll, fill out our <<EnrollNow.adoc#Enroll Now,online application>> and we will get back to you shortly.