= Enrollment Process and Fees
:sectanchors:

include::src/html/adoc/navbar.adoc[]


++++
       <div id="wrapper">
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href="#_enrollment_process">Enrollment process</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_preferential_acceptance">Preferential Acceptance</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_lottery">Lottery</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_registration_packet">Registration Packet</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_withdrawal_and_transfer_information">Withdrawal and Transfer Information</a>
                    </li>
                </ul>
            </div>
++++

== Enrollment Process
WIT will enroll any Utah student entering 9th, 10th, 11th, or 12th grade in the 2015-2016 school year, subject available to capacity. Admission to the Wasatch Institute of Technology is not limited based on ethnicity , national origin, gender, religion, income level, creed, color, disabling condition, or proficiency in the English language. We may deny admission to any student under any of the following circumstances:

* If a student has been expelled from any other public school during the preceding 12 months
* To protect the health or safety of a current student or staff member
* The student's admission would disqualify the school from federal funding

To apply for admission to the Wasatch Institute of Technology, complete our <<EnrollNow.adoc#Enroll Now,online application>>. We're accepting applications now!

== Preferential Acceptance
Preference for acceptance to the school (up to 5% of our total student capacity) is given to: 

. Child of a parent who is currently employed full-time at WIT
. Child of a parent who was a Founding Member of WIT
. Sibling of a current WIT student

The remaining positions at the Wasatch Institute of Technology will be filled either automatically or through an open lottery. If the number of students that have applied to WIT by the cutoff date does not exceed our remaining program, class, or grade level capacities, we will admit all of the students that have applied and continue to accept applications on a first-come, first-serve basis. If the number of applications exceeds our capacity, new WIT students will be selected for enrollment through an open lottery.

== Lottery
The enrollment lottery will be held at the school or in a public setting on or before June 15th. All applicants and their parents are invited to attend. All applicant numbers will be drawn randomly. All applicants will be notified of their acceptance or wait list position not later than June 30th. Students accepted for admission will receive a written offer of admission. If our offer of admission is not accepted by the deadline specified therein or if the enrollment is declined, the top-listed student on our wait list will be extended and offer of admission.

== Registration Packet
Students admitted into WIT must complete a registration packet within 30 days or prior to attending WIT, whichever comes first. The registration materials include, but are not limited to:

* Student Information form
* Medical Information and Release form
* Immunization records
* Copy of the student's birth certificate
* WIT policy acceptance form
* Copy of IEP or 504 plan for Special Education students (if applicable)
* Economically disadvantaged forms (if applicable)

If the registration materials are not received on time or if the incoming student records indicate that the student has been expelled from a public school in the preceding 12 months, the student will be removed form our list of accepted students and replaced with a student on our wait list. Under extenuating circumstances and if a written request is received prior to the registration packet deadline, an extension of time ot submit the completed registration packet may be granted by the School Director.

== Withdrawal and Transfer Information
Students wishing to transfer from another school to the Wasatch Institute of Technology follow our regular enrollment process.

Pursuant to http://le.utah.gov/code/TITLE53A/htm/53A01a050605.htm[Utah Code 53A-1a-506.5], the parent of a WIT student may withdraw the student from WIT for enrollment in another charter school or a school district by submitting to us:

* On or before June 30, a notice of intent to enroll the student in the student's school of residence for the following school year
* After June 30, a letter of acceptance for enrollment in the student's school district of residence for the following year
* A letter of acceptance for enrollment in the student's school district of residence in the current school year

Unless provisions have previously been made for enrollment in another school, WIT will immediately notify the district of residence, which shall enroll the student in the resident district and take such additional steps as may be necessary to ensure compliance with law governing school attendance. 
