= How do we learn?

Nothing else is as interesting as discovering our own interests/abilities

https://www.lds.org/church/news/simple-habits-help-us-live-with-purpose-and-real-intent?lang=eng&cid=email_inspiration_and_news_2_2015_truepurpose_cta

It is through living a deliberate, focused life that we will find
success

“The compounding effect of daily disciplines, with purpose and real
intent, can make a big difference in all areas of your life,” he said.
“It can mean the difference between struggling through an ordinary life
or being immensely successful

Having so many choices and opportunities can be a blessing and a curse.
“Too many choices, and the fear of making bad decisions, often lead to
decision paralysis.”

Too often people question whether a better option is around the corner,
so they wait and choose nothing. That passive state is like being in a
lifeboat with nothing but rolling waves in every direction and not
knowing which way to row. A glimpse of land is needed to provide both
motivation and purpose. “People who don’t maintain a clear sense of
purpose are drifters. Drifters allow the tides of the world to decide
where they are going.”

The antidote for that passive state is living with purpose and real
intent.


“Living with ‘real intent’ means understanding the ‘why’ and being aware
of the motives behind your actions. Socrates said, ‘An unexamined life
is not worth living.’ Ponder how you spend your time and ask yourself
regularly, ‘Why?’ This will help you develop the ability to see beyond
the moment. It’s far better to look ahead and ask yourself, ‘Why would I
do that?’ than to look back and say, ‘Why, oh, why did I do that?’

Three small and simple things that can help us maintain our eternal
focus are:
1. Do your best
2. ?
3. ?

“Teachers past and present have pleaded with us to do small and simple
things like turning in homework. So why doesn’t everyone do them?
Perhaps one reason is that we don’t necessarily see dramatic negative
consequences if we miss a day or two—just as your teeth don’t all decay
and fall out the first time you don't brush. Most of the consequences,
positive and negative, will come later, over time. But they will come.”

It is through living a deliberate, focused life that individuals will
find success and become more like their Heavenly Father.

“Start now. Live a purposeful life. Put the power of the compounding of
daily disciplines in place in the important areas of your life. I
promise that in a year from now, you will either be glad you started
today, or you will wish you had.”

== How we Learn

== Sprint 0 - Boats

== Music Sprint

== Water Sprint

== Cycles Sprint

== Space Sprint