= How do we learn?
:sectanchors:

include::src/html/adoc/navbar.adoc[]

++++
       <div id="wrapper">
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href="#_agile_software_development_methodology">Agile Methodology</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_next_generation_education">Next Generation Education</a>
                    </li>
                </ul>
            </div>
++++

== Agile Software Development Methodology 
On February 11-13, 2001, 17 software developers from around the country met at Snowbird, Utah to discuss lightweight software development methods (see http://agilemanifesto.org/history.html[Agile history]).  As a result of their meeting, they published the http://agilemanifesto.org[Agile Manifesto] that established the core values of the Agile software development approach.  The Wasatch Institute of Technology has adapted the principles underlying the Agile Manifesto for educational use:

[cols="1*"]
|===

| Our highest priority is education of our students through early and continuous achievement of curricular learning objectives.

| Welcome changes in learning objectives, curriculum, and instructional methods.  Agile processes harness change for the student’s competitive advantage.

| Deliver evidence of learning objective mastery frequently, from a couple of weeks to a couple of months, with a preference to the shorter timescale.

| Students and staff must work together daily throughout the school year.

| Build projects around motivated individuals.

| Give students and staff the environment and support they need, and trust them to get their jobs done.

| The most efficient and effective method of conveying information to and within a teaching team is face-to-face conversation.

| Interdisciplinary student-initiated and created work is the primary measure of progress.

| Agile processes promote sustainable learning.

| The staff and students should be able to maintain a constant pace indefinitely.

| Continuous attention to technical excellence and good design enhances agility.

| Simplicity–the art of maximizing the amount of work not done–is essential.

| The best plans, requirements, and designs emerge from self-organizing teams.

| At regular intervals, the team reflects on how to become more effective, then tunes and adjusts its behavior accordingly.

|===

In use for over 10 years, the Agile methodology has provided the following benefits for software development:

* *Increased employee job satisfaction*.  The team-centered shared responsibility and self-direction philosophies allow team members to work at a more regular, sustainable pace.  This not only increases employee job satisfaction, but engages employees more, increases an employee’s quality of work, and reduces their overtime hours.  This can also potentially lead to significant gains in productivity when creative solutions are found by the team.
* *Increased quality*.  Software development teams that adopt an Agile methodology  report a minimum 10% quality improvement; the median improvement is 63% (Source:  Cohn, Mike. Succeeding with Agile. Addison-Wesley 2010, p. 15),  Quality is improved is through better engineering practices; testing regularly and often as soon as possible (since testing at the end often gets eliminated); and moments of group reflection and suggestions for improvement fostered by the sprint retrospective meeting.
* *Higher team productivity*.  Learning to think and work as a team causes collaboration to go to new highs.  In this world of shared responsibility, team members think collectively of tasks, not individually.  As team members start to see the vision for the finished product become reality, they become more excited and passionate; and as passion increases, so does productivity.
* *Increased stakeholder satisfaction*.  With a better alignment of goals, the ability to regularly adjust priorities, delivering the highest-value items first, the improved visibility of the process, and a faster time to market, Agile leads to increased stakeholder satisfaction–78% of surveyed individuals believe that using an Agile process has led to increased stakeholder satisfaction (Cohn, p. 16).
* *Continuous learning and improvement*.  To realize all the benefits of Agile, each team must constantly seek out new knowledge and share it with others.  Since teams are afforded both flexibility and time to implement a solution, they can often discover new or improved ways of doing things.  Team members then have many ways of sharing this improvement:  in the daily standup meeting, during the sprint retrospective, in communities of practice, or even in an impromptu meeting in the team’s shared work space.

At WIT, we expect to see these same benefits through our educational adaption of the Agile software development methodology.

== Next Generation Education
Our educational implementation of Agile coupled with Pennant (our student information system) is what we call Next Generation Education (NGE).  In short, NGE is a flexible, objective-based approach, where students work in teams, present their projects, and gain real-life work experience.  Developed from years of real teaching and incorporating many ideas promoted by educational reformists, Next Generation Education provides a remarkably different educational experience focused on accountability, flexibility, transparency, creativity, and teamwork. Outlining our typical workflow will illustrate how Next Generation Education works.

=== Teachers
Teachers are bound together in small, interdisciplinary, self-organizing, and accountable teams known as Teaching Teams.  During sprint planning, team members select the most important learning objectives to cover in the upcoming sprint.  When possible, the team determines a theme for the sprint and identifies ways to integrate the subject areas.  Since teachers would have previously estimated the amount of class time required to cover each learning objective, the team negotiates the teaching schedule and class times for the coming sprint.

During the sprint, Teaching Team members facilitate learning sessions pertaining to the sprint’s learning objectives.  These sessions should engage the students in discovering the ideas associated with each objective and the connections between objectives as they apply what they have learned to accomplish meaningful work.  Frequently this will be done through problem-based learning.

Every day, the Teaching Team meets together for the Daily Scrum.  Each team member reports what they accomplished yesterday and commits to what they will do today.  When trouble arises, the team can adjust priorities, re-balance sprint tasks, solicit help, and identify and remove any impediments they may encounter.

When team members are not leading learning sessions, they may be working with students in Study Hall, engaged in planning, assessing student portfolio artifacts, or participating in Teacher Communities of Practice (TCOP).  In Subject Area TCOPs, the teachers across Teaching Teams join together for grading, brainstorming, discussion, readings, joint planning, curriculum development, problem solving, etc.  Interest TCOPs are groups of teachers crossing team and subject area boundaries that meet together because of their passion or interest around a particular topic, technology, idea, approach, or vision.

The Teaching Team ends its sprint with a sprint retrospective.  Here the team identifies what went well during the sprint, what didn’t go well during the sprint, and what can be done better next sprint.  They also identify what they should continue doing and stop doing.  Answers to these questions are added to the master retrospective list.  Given the master list in its entirety, the team will collectively commit to work on one or more of the top items on the list in the coming sprint.  How well the team did on these items will be evaluated at the next sprint retrospective.

The Teaching Team members are the primary participants in the sprint retrospective, but other stakeholders may be invited to participate, such as a student presenting an exceptional portfolio artifact.  When students do not adequately achieve mastery of a given learning objective, subsequent strengthening activities can be planned in an upcoming sprint.

Typically on a monthly basis, the Teacher Achievement Specialist will hold a personal management interview with each member of his Teaching Teams to see how they are doing, resolve concerns, maintain accountability, and empower the employee to fulfill their responsibilities.  This interview begins by following up on recent assignments and reviewing the teacher’s efforts on the master retrospective list.  The remainder of the interview varies depending on circumstances, but may include: discussion and resolution of administrative or organizational problems; training in specific skills; solving interpersonal problems; discussing what is happening in the organization; identifying individual and organizational needs; and discussion of personal problems as appropriate. The interview ends by reviewing assignments that were made and ensuring that they are mutually understood.

=== Students
Students are responsible for demonstrating their mastery of the learning objectives by the end of each sprint, yet have significant flexibility in how they do it.  These portfolio artifacts, ideally crossing subject area boundaries, are completed individually or in small groups during Study Hall and can take many forms:  written papers, conducted experiments or simulations, videos, tutorials, community service, computer programs, etc.  Each day, students update their progress on their artifacts in Pennant; parents can view this progress and the actual artifacts.  Besides working on portfolio artifacts, Study Hall is the time for students to prepare for upcoming learning sessions and to receive additional help from their peers and Teaching Team members.

Added to the mix of Study Hall and learning sessions are reading time, daily exercise, and the student-run store.  During reading time, students are free to read nearly anything across genres and from all disciplines.  Students will record their observations, thoughts, comments, and recommendations on their reading blog to foster a culture of literacy.  Facilitated by the library staff, students may join with others across Teaching Teams to read, discuss, and share as they discover a book together.  During exercise time, students and staff will engage in active physical activity to strengthen the body and invigorate the mind.  The student store will serve the school community and the public at large as students learn firsthand the details of running a business.  The day ends as students and staff work together to clean the building for the next day.

At the end of a sprint, the students will participate in a sprint retrospective meeting led by a member of the Teaching Team.  This sprint retrospective meeting will be held prior to the Teaching Team retrospective so that pertinent student feedback can be included.  This meeting will be similar in structure to the retrospective held by the Teaching Team, but more students will present their portfolio artifacts.

Every day begins with students meeting with their mentoring group, which consists of students across Teaching Teams and a staff member.  This mentoring group, formed when students first entered the school, will remain together throughout their time at WIT. The group will provide regular support, guidance, and assistance as they read, write, discuss, and learn about topics designed to prepare students for life.  Besides spending time together, the staff member’s task is to look holistically at the mentee, ideally becoming a friend and advocate.

Twice per year at the end of each semester, students have the opportunity to present their best work in the semester showcase.  Similar in format to a science fair, the semester showcase presents student work from the Student Communities of Practice as well as from the Teaching Teams.  Parents, family members, and the community are welcome to attend.

Students will graduate from the Wasatch Institute of Technology with a high school diploma and a corresponding technical certificate.  This certificate will indicate which program of study the student participated in, a summary of how well he mastered each area of learning objectives, and an overall achievement level for the program of study.

Interested and qualified students can participate in our job placement program, where we work with companies to fulfill their IT staffing needs with our current and former students.   Participating students will decide which pieces of their portfolio can be shared with potential employers.

=== Staff
The Student Achievement Team, working together to ensure success for students at all levels, carefully monitors student progress via Pennant and intervenes during significant variations in student performance.  The Teacher Achievement Specialist shelters the Teaching Teams from outside distractions and removes any impediments to effective teaching.  As a master teacher, the Teacher Achievement Specialist frequently works one-on-one with individual teachers to plan and execute successful learning sessions.  The Core Administrative Team enables the staff, represents the school externally, and facilitates the gathering and consideration of feedback and complaints.

=== Conclusion
Our educational adaption of Agile goes far beyond project management to impact nearly every aspect of the school and will revolutionize the learning environment at the Wasatch Institute of Technology.  This revolution will cause both teachers and students in self-organizing, accountable teams to take active roles in the learning process.  By collaborating to solve real-world problems across discipline boundaries and grade levels, students and teachers will go beyond a mere acquisition of knowledge to cultivating capacities to both think and to solve problems.  These learners will become generalists capable of rapidly adapting to a variety of situations in our ever-changing world.  As an added benefit, our students with the right skills and experience can obtain meaningful and significant employment in a mid-level position, such as a junior software engineer or a systems administrator. The average Utah starting salary for these positions is $40,000 – $60,000.

We are excited to offer our students something this revolutionary.  Our doors opened August 2014, and we will begin our second year August 2015.  Would you like to become a <<EnrollmentProcess.adoc#Enrollment Process,student>> or an <<WorkWIT.adoc#I can teach?,employee>>?