= Things to Love About WIT
:sectanchors:

include::src/html/adoc/navbar.adoc[]


++++
       <div id="wrapper">
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href="#_student_experiences">Student experiences</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_school_culture">School culture</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_wit_student_profiles">WIT student profiles</a>
                    </li>
                </ul>
            </div>
++++

== Student Experiences 
WIT has now completed its first operational year. Some of our current students have written a little bit about their experiences:

_Cameron H:_ +
Coming to WIT is different from most schools, considering all of the content that they offer. I think that the number one reason I came here was the way that they teach. Considering the sprint, I think that as a hands-on person, the deliverables are a good way to learn. We get a feel for learning that we didn't get anywhere else. We also get a lot of freedom here, considering that we have a lot of privileges. Not abusing them gives you so many possibilities.

_Taylor:_ +
I like being a WIT student. I think this is the first time I have ever actually learned something useful in school. I have experience building computers, and I wanted to expand my knowledge of them, so I came here. I would recommend this school to anyone with an interest in computers or technology.

_Jake:_ +
At first, students had a rough time adjusting to the way WIT worked, but as time went on, it started to flourish and everyone has started to work together better now that we know each other. Now that we're in a state where we can all work together and be accepting of each other, the learning environment is very healthy and we're all doing well.

_Mike:_ +
I was really skeptical at first. Well, now that I've been here for a while, I've adjusted to the real world way WIT operates. The skepticism was just me being afraid of the unknown. It's a new school, so I wasn't prepared for any of the teachers or how their teaching styles are different from those at public schools. Now that the teachers and students are adjusted, it's easier to understand the work that we've been given and work together as a team.

_Cameron B:_ +
WIT’s  a place where you can actually feel like you earned that perfect A. It's a place where kids actually earn their grade––I feel like with as hard as I work and the effort that I put in I would have had As in public school, but here I've received 2s. WIT is like a place of work rather than a school. We have objectives and requirements to meet. It gives the same atmosphere as a workplace. It makes you want to work harder. Yeah, that's what's great about WIT.

== School Culture
WIT offers a unique approach to learning that incubates a close-knit, safe community. By focusing on hands-on learning, project based work, and real world experience, students develop strong working relationships with their peers and teachers. Students get to see what it would be like to work in a job environment, and develop skills necessary to succeed in life.

== WIT Student Profiles
WIT students have a wide variety of interests and career plans. Several students have shared their interests and how they feel WIT is helping them accomplish their goals:

_Austin:_ +
I want to be a web developer.  I think that WIT will help me get a head start at understanding the tech industry, while giving me a hands-on portfolio and experience in my field.

_Sophie:_ + 
I want to be a doctor, but I recognize that technology is becoming increasingly prevalent in our world and the workplace.  WIT will give me the tech experience that I need to approach that, while teaching me what I will need to succeed in my higher education, and beyond.

_Mike:_ + 
I want to be a programmer.  WIT will give me the necessary skills to succeed, and teach me the skills that will help me learn and grow.

_Cameron H:_ +
I want to be a game developer.  I think that the way WIT teaches is innovative, and it makes learning fun.

_Savannah:_ +
I want to be a cosmetologist.  I think that WIT’s learning and teaching style allows me to learn far more than I would at a normal public high school.

_Taylor:_ +
I want to own a computer repair company.  WIT is teaching me the skills I need to both repair those computers, and understand what’s going wrong when I do.
