= Things to Love About WIT
:sectanchors:

include::src/html/adoc/navbar.adoc[]


++++
       <div id="wrapper">
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href="#_student_experiences">Student experiences</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_school_culture">School culture</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_wit_student_profiles">WIT student profiles</a>
                    </li>
                </ul>
            </div>
++++

== Student Experiences 
Overall, student feedback has been overwhelmingly positive for the WIT methods of teaching. Students have all said that they felt listened to and respected by their teachers, compared to their prior school experiences. One point that was frequently commented upon was that the smaller class sizes allowed for them to have better relationships with both their teachers and their peers, and contributed to a better learning environment.
Students' favorite field trips have been the Salt Lake County Water Symposium during the Water sprint, the trip to BYU to hear the founder of Pixar speak, and the play “Is He Dead?” at Hale Centre Theater during the Cycles sprint. Favorite projects have included the cardboard boats during the boat sprint (our first), the crystal radios built in the 1920s sprint, and the science fiction/fantasy short stories written during the space sprint.

_Cameron H:_
Coming to WIT is different from most schools, considering all of the content that they offer. I think that the number one reason I came here was the way that they teach. Considering the sprint, I think that, as a hands-on person, the deliverables are a good way to learn. We get a feel for learning that we didn't get anywhere else. We also get a lot of freedom here, considering that we have a lot of privileges. Not abusing them gives you so many possibilities.

_Taylor:_
I like being a WIT student. I think this is the first time I have ever actually learned something useful in school. I have experience building computers, and I wanted to expand my knowledge of them, so I came here. I would recommend this school to anyone with an interest in computers or technology.

_Jake:_
At first, students and staff had a rough time adjusting to the way WIT worked, but as time went on, it started to flourish and everyone has started to work together better now that we know each other. Now that we're in a state where we can all work together and be accepting of each other, the learning environment is very healthy and we're all doing well. And it's not just the students- the teachers are, too.

_Mike:_
I was really skeptical at first. Well, now that I've been here for a while, WIT has gotten a lot better. I believe that this school teaches well enough that I'll graduate. The skepticism was just me being afraid of the unknown. It's a new school, so I wasn't prepared for any of the teachers or how their teaching styles are different from those at public schools. Now that the teachers and students are adjusted, it's easier to understand the work that we've been given and work together as a team.

== School Culture

== WIT Student Profiles