= Our Mission and History
:sectanchors:

include::src/html/adoc/navbar.adoc[]

++++
       <div id="wrapper">
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href="#_mission_statement">Mission Statment</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_core_values">Core Values</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_wit_s_history">WIT's history</a>
                    </li>
                </ul>
            </div>
++++

== Mission Statement
The mission of the Wasatch Institute of Technology is to prepare tomorrow’s Software Engineers through _Next Generation Education_. 

By teaching skills required for the jobs of the 21st century, WIT students will form the foundation for tomorrow’s innovation economy. Not only will WIT students graduate with traditional high school diplomas, they will have a tremendous career advantage since they will understand technology well enough to use it in truly innovative ways–thus enabling the true computer revolution.

== Core Values
As we work to achieve our mission, we value: 

* *Innovation and creativity:* We follow and create best practices, not limiting ourselves to the box. 
* *Teamwork and responsibility:* When we see something that needs to be done, we take care of it. 
* *Honesty and transparency:* We are open about what we do, how we do it, and what we can do better. 
* *Equality and compassion:* We are valued for what we do in our meritocracy and are concerned about our collective welfare. 
* *Ethics and integrity:* We are role models whose behavior is consistent both in and out of the school.

== WIT's History
The Wasatch Institute of Technology is the brainchild of David Moss, our current School Director. After teaching college-level computer science full-time for nearly a decade, he was baffled by the declining abilities of incoming computer science students. Despite the fact that these incoming students had more exposure to computers than their predecessors, they were less capable of doing anything useful with them. 

Rather than bemoan the declining capabilities, he worked to establish a computer science-focused high school accessible to as many students as possible. Combining his expertise as a network administrator, software developer, and ScrumMaster, David adapted the Agile software development methodology for education. The result is a <<Sprint.adoc#_sprint_planning,unique learning environment found nowhere else>>. 

Based on our <<OurMission.adoc#_core_values,core values>>, WIT is learning laboratory, a place where we can continually try new things, innovate, and iterate as we work to prepare tomorrow's Network/Systems and Software Engineers through _Next Generation Education_. 

Learn more about <<Sprint.adoc#_sprint_planning,how WIT works>>.