= Policies and Procedures

== WIT Code of Conduct
We think beyond ourselves. 

We treat the school and it’s people with kindness and respect. 

We are honest, can be trusted, and trust others. 

We do the right things for the right reasons. 

We are ethical, moral, and follow the law. 

We do our best, work hard, and have fun. 

We are innovative, passionate, focused, creative, and resourceful. 

We are responsible and don’t make up excuses. 

We work together as a team and help each other. 

We are ready to learn. 

We behave well to maximize our freedom. 

We clean up after ourselves and others. 

We talk when appropriate.

== WIT Dress Code
We respect ourselves and others with the way we dress. 

Our clothes won’t embarrass, offend, or distract others. 

Our clothing is activity appropriate. 

Our clothes fit. 

We wear clothes underneath sheer clothing or clothing with holes. 

Our underwear isn't seen.

== Electronics Use
Electronics may be used in class if they are not a distraction. 

Electronics will be put away when the teacher asks. 

Music may be listened to during individual or group work if it is not a distraction to others. One ear must be free of ear buds when working with others.

== Food and Drink
Students may eat and drink in class IF… 

* A teacher grants permission. 

* It is not a distraction to others. 

* Drinks are in closed containers 

* Gum and Candy isn’t seen or heard. 

* All messes are cleaned up completely

== Hygiene
We come to school clean.

== Language
We use verbal and nonverbal language that will not offend those around us.

== Public Displays of Affection
We do not show public displays of affection during school hours or school activities.

== Drugs
No drugs, alcohol, cigarettes, or tobacco. Prescription drugs are allowed if the office is informed and if kept in a perscription bottle.

== Weapons
No weapons or look alike weapons are allowed.

== Tools
Power tools, saws, and other tools may be used for school related projects, in a controlled and supervised environment. The use of tools is a privilege, not a right, and can be retracted if tools are being used irresponsibly.