= SCOPS

== What are SCOPS?
A Student Community of Practice (SCOP) is a group that comes together because of their passion or interest around a particular topic, technology, idea, approach, or vision. These SCOPs allow individuals a chance to explore areas of interest in an open, participatory, and curricularly safe way. To foster creativity and freedom to try new things, students are generally not graded in their SCOPs; however, attendance is taken. The ideas for a SCOP may come from a student, as long as a proposal detailing which common core standards are met. As part of our regular program of instruction, all students, staff, and many volunteers participate in SCOPs throughout the school year daily during the first and last period of the day on Tuesdays, Thursdays, and Fridays, and during the first two periods of the day on Mondays and Wednesdays.

The genius of the SCOPs is the flexibility and freedom they afford students, their small size, and how they will solidify the school community. Freed from normal curricular constraints, SCOPs are an outlet for students to determine what and how they explore new things. The large number and diversity of these SCOPs should provide ample opportunities for the mind, the body, and the spirit. Some sample SCOPs could be: 

* Students interested in archaeology host a guest speaker from the Utah Museum of Natural History, then take a day trip to Nine Mile Canyon 

* Students interested in solar energy build solar powered toy cars 

* Students interested in gardening compare the success of planting in earth boxes, square foot gardens, and traditional row-crop planting 

* Students interested in drama practice and present a play 

* Students interested in cooking host guest chefs to teach them to prepare native dishes from throughout the world 

* Students interested in science give a science presentation to an elementary school class 

* Students interested in skiing participate in a learn to ski program 

* Students interested in singing form a mixed chorus 

* Students interested in photography visit carious photogenic sites as they learn about different types of photography, such as black and whit, portrait, landscape architectural, etc. 

* Students interested in Shakespeare read and analyze one of the plays, then go see a Shakespearean play 

* Students interested in the stock marked learn about commodities trading, mutual funds, and traditional stocks; each student invests a small amount as they all track its performance 

* Students interested in a foreign language learn about the culture and vocabulary, and converse with a fluent speaker of the language 

* Students interested in history make a video documentary on a particular event or time period 

* Students interested in dance learn ballroom dancing techniques, which are showcased at a school-wide dance 

* Students interested in meditation learn and practice yoga 

* Students interested in buying a car host a guest speaker mechanic that points out things to look for when purchasing a car; students then research safety ratings, depreciation, and typical costs for select models; students then visit a few car dealerships to see the actual car 

* Students interested in creating video games learn about the computer game industry; guest speakers come in to talk about their roles in a gaming company; students visit a local computer game maker; students then work together to write their own computer game 

Unfortunately, not all SCOP ideas will become an actual SCOP, as there are a limited number of classrooms available for use by a SCOP. The SCOP may also be rejected if there are not enough students who show interest in the SCOP who would be willing to participate.

SCOPs will increase school unity, as they pull together students across Teaching Teams with school staff. The SCOPs also afford parents, grandparents, and guardians an excellent opportunity to meaningfully share their talents and interests, either as an advisor or as a guest speaker during an SCOP. The number of adults participating can reduce the student size of the SCOP, which in turn can increase the number and diversity of available SCOPs. The smaller SCOPs might also encourage people who would not ordinarily participate to join with us: consider an immigrant mother. Although she doesn’t speak English, with her son serving as translator and only four others in the cooking SCOP, she might be willing to demonstrate preparation of some ethnic dishes. For special events, students could invite other students to attend the SCOP.

Depending on the size of the SCOP, one or more adult advisors will be present. These advisors can be anyone with a direct tie to the school: a teacher, a school employee, a parent or grandparent of a student, etc. Although the advisor may not be an expert, they should at least have a personal interest in the SCOP’s focus area and must be willing to support and attend the SCOP. The advisor’s responsibilities are to track student attendance and advise the SCOP in the planning and execution of their activities. The small size of an SCOP will allow the group to be more active and mobile: it is a lot easier to conduct a field trip with 6 participants than with 200.

Students need to schedule SCOP classes when they are available, and cannot choose not to be in a class when SCOP classes are in session. We firmly believe that Student Communities of Practice will provide an extraordinary learning experience not only for the students, but the advisors and outside participants as well.

== The SCOP Proposal 
SCOPs are ideally student driven. Students create a SCOP proposal that outlines the purpose of the SCOP, the interest in the SCOP, the material covered in the SCOP, and the objectives fulfilled by the SCOP. That is then delivered to the student’s advisor, who follows through with getting Administrative approval, as well as insurance approval. If the SCOP proposal is not quite the quality needed to get approval, the advisor will inform the student that revision is needed and can provide support to insure that the SCOP gets approved. Once the SCOP proposal has received administrative and insurance approval, the student will be informed, and the class can begin. Students should be fully prepared to start the SCOP even before it has been approved, so that the SCOP can start immediately. The teaching team can then help make sure the SCOP appears on the schedule, and that other students can sign up for the class.

== Current SCOPS