= Sprints
:sectanchors:

include::src/html/adoc/navbar.adoc[]

++++
       <div id="wrapper">
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href="#_sprint_planning">Sprint planning</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_sprint_document">Sprint document</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_daily_standups">Daily standups</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_sprint_deliverables">Sprint deliverables</a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#_sprint_presentations">Sprint presentations</a>
                    </li>
                     <li class="sidebar-brand">
                        <a href="#_sprint_retrospective">Sprint retrospective</a>
                    </li>
                </ul>
            </div>
++++

== Sprint Planning
Before each sprint, the teaching team compiles information gathered from the last sprint’s retrospective (covered in depth below). They use this information to create the next sprint and sprint document (covered in depth below). The teaching team lays out the next sprint’s theme, classes, objectives, deliverables, field trips, guest speakers, and extra activities before the sprint starts. This allows them to draw information from last sprint to implement in the next sprint.

== Sprint Document 
At the beginning of every sprint, a sprint document is created and posted where all students, teachers, and parents have access to it. This sprint document outlines the entire sprint; by breaking down each deliverable that is expected to be completed into the individual objectives associated with it. Students can then pinpoint specific objectives that they need to focus on and get extra help with, as well as what things they will be getting credit for by completing the objective.

== Daily Standup
In morning advisory, the advisor talks with each student about their progress on each deliverable they have been assigned. Students then update their row on the deliverable progress board, by moving each individual deliverable from one section to the next. This gives a visual of where each deliverable is—0%, 25%, 50%, 100%, waiting for feedback, revision, and completed. Along with seeing their own progress, students can see approximately where their peers are in the process, and if they are on track to finish by the end of the sprint.

== Sprint Deliverables
Sprint deliverables are projects that allow students to show mastery of the learning objectives they have been tasked with learning. Usually, sprint deliverables are projects that are designated by the teacher, but are intended for students to build upon to achieve a higher score. Occasionally, students will be asked to create a deliverable that shows their mastery of the objectives. This main deliverable usually receives support from a series of smaller deliverables that have been designated by the teacher, to help students understand what they are supposed to be showing.

== Sprint Presentations
At the end of the sprint, each student is expected to deliver a presentation to the rest of the school, showing what they learned based off of the objectives they have mastered. This allows the teachers to see what the students have learned, as well allowing the students to see how their peers learned the objectives differently. Students are not told how to present what they learned to the rest of the school, because everyone learns differently. Instead, the presentation they develop is unique, just like their learning style, and they are expected to show that to the rest of the school.

== Sprint Retrospective 
The sprint retrospective occurs on the last day of the sprint, in each of the advisory groups. The advisor leads the discussion, and students provide back input on what went well during the sprint, what didn’t go well during the sprint, what to continue doing next sprint, what to stop doing next sprint, and what to start doing next sprint. This information allows the teaching team to better develop the next sprint so that each student can reach their full potential and provide quality work. Every student has equal opportunity to provide their opinion on how they feel everything is progressing, and every student’s opinion is weighted equal. The teaching team takes all of the advisories retrospectives into account when they have their end of sprint retrospective as well as when they start the sprint planning for the next sprint.