= Is WIT For Me?

== The Perfect WIT Student

== Girls in IT
Workers in IT are overwhelmingly male. However, IT is one of the only places in which the wage gap between white female and male employees with the same qualifications isn't $0.77 to $1. So, you may ask what WIT's stance is on females. While our student body does not represent it, we want female students to get into technology. Even while they aren't typically pushed towards STEM fields, they're just as intelligent as their male peers. We want female students, and employers want female employees.

== What to Expect
The day starts at 8:30 with a fifteen-minute advisory, and then classes begin (including SCOPs). Lunch is from 11:30-12:15, followed by a 15 minute reading session. Classes resume until 3:15, with afternoon advisory and the day ends at 3:30.

Starting at WIT, you should know that you need to take charge of your actions and be very responsible. The teachers won't nag you to get your work in if you don't do it. You should expect freedom, but you should also expect to be held accountable for your actions and face the consequences (i.e. less time at luch, not picking your classes, etc.).

== Student Supplies

== Getting to WIT

== Location

== Shadowing